ERROR - 2024-07-06 05:24:55 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'digisoft' in C:\xampp\htdocs\plantilla\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\plantilla\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'digisoft', 3306, '', 0)
#1 C:\xampp\htdocs\plantilla\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\plantilla\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\plantilla\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\plantilla\app\Models\home_model.php(22): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\plantilla\app\Controllers\Home.php(29): App\Models\home_model->obtenerUsuarios()
#6 C:\xampp\htdocs\plantilla\system\CodeIgniter.php(933): App\Controllers\Home->obtenerUsuarios()
#7 C:\xampp\htdocs\plantilla\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\plantilla\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\plantilla\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\plantilla\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\plantilla\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'digisoft' in C:\xampp\htdocs\plantilla\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\plantilla\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\plantilla\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\plantilla\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\plantilla\app\Models\home_model.php(22): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\plantilla\app\Controllers\Home.php(29): App\Models\home_model->obtenerUsuarios()
#5 C:\xampp\htdocs\plantilla\system\CodeIgniter.php(933): App\Controllers\Home->obtenerUsuarios()
#6 C:\xampp\htdocs\plantilla\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\plantilla\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\plantilla\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\plantilla\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\plantilla\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-07-06 05:24:55 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'digisoft'
[Method: POST, Route: HOMObtenerUsuarios]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `cat_usuarios`', [], false)
 3 APPPATH\Models\home_model.php(22): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(29): App\Models\home_model->obtenerUsuarios()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->obtenerUsuarios()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-07-06 20:53:50 --> mysqli_sql_exception: Unknown column 'estado' in 'field list' in C:\xampp\htdocs\plantilla\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\plantilla\system\Database\MySQLi\Connection.php(312): mysqli->query('UPDATE `cat_usu...', 0)
#1 C:\xampp\htdocs\plantilla\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `cat_usu...')
#2 C:\xampp\htdocs\plantilla\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `cat_usu...')
#3 C:\xampp\htdocs\plantilla\system\Database\BaseBuilder.php(2508): CodeIgniter\Database\BaseConnection->query('UPDATE `cat_usu...', Array, false)
#4 C:\xampp\htdocs\plantilla\app\Models\home_model.php(95): CodeIgniter\Database\BaseBuilder->update(Array)
#5 C:\xampp\htdocs\plantilla\app\Controllers\Home.php(70): App\Models\home_model->HOMEditarUsuario(Array)
#6 C:\xampp\htdocs\plantilla\system\CodeIgniter.php(933): App\Controllers\Home->HOMEditarUsuario()
#7 C:\xampp\htdocs\plantilla\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\plantilla\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\plantilla\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\plantilla\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\plantilla\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2024-07-06 20:53:50 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'estado' in 'field list'
[Method: POST, Route: HOMEditarUsuario]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2508): CodeIgniter\Database\BaseConnection->query('UPDATE `cat_usuarios` SET `usuario` = :usuario:, `contraseña` = :contraseña:, `estado` = :estado:
WHERE `idusuario` = :idusuario:', [...], false)
 2 APPPATH\Models\home_model.php(95): CodeIgniter\Database\BaseBuilder->update([...])
 3 APPPATH\Controllers\Home.php(70): App\Models\home_model->HOMEditarUsuario([...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->HOMEditarUsuario()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-07-06 20:53:50 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'estado' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `cat_usuarios` SET `usuario` = \'principal\', `contraseña` = \'Pr1ncipal\', `estado` = \'S\'
WHERE `idusuario` = \'1\'')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `cat_usuarios` SET `usuario` = \'principal\', `contraseña` = \'Pr1ncipal\', `estado` = \'S\'
WHERE `idusuario` = \'1\'')
 3 SYSTEMPATH\Database\BaseBuilder.php(2508): CodeIgniter\Database\BaseConnection->query('UPDATE `cat_usuarios` SET `usuario` = :usuario:, `contraseña` = :contraseña:, `estado` = :estado:
WHERE `idusuario` = :idusuario:', [...], false)
 4 APPPATH\Models\home_model.php(95): CodeIgniter\Database\BaseBuilder->update([...])
 5 APPPATH\Controllers\Home.php(70): App\Models\home_model->HOMEditarUsuario([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->HOMEditarUsuario()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-07-06 20:53:50 --> [Caused by] mysqli_sql_exception: Unknown column 'estado' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('UPDATE `cat_usuarios` SET `usuario` = \'principal\', `contraseña` = \'Pr1ncipal\', `estado` = \'S\'
WHERE `idusuario` = \'1\'', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `cat_usuarios` SET `usuario` = \'principal\', `contraseña` = \'Pr1ncipal\', `estado` = \'S\'
WHERE `idusuario` = \'1\'')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `cat_usuarios` SET `usuario` = \'principal\', `contraseña` = \'Pr1ncipal\', `estado` = \'S\'
WHERE `idusuario` = \'1\'')
 4 SYSTEMPATH\Database\BaseBuilder.php(2508): CodeIgniter\Database\BaseConnection->query('UPDATE `cat_usuarios` SET `usuario` = :usuario:, `contraseña` = :contraseña:, `estado` = :estado:
WHERE `idusuario` = :idusuario:', [...], false)
 5 APPPATH\Models\home_model.php(95): CodeIgniter\Database\BaseBuilder->update([...])
 6 APPPATH\Controllers\Home.php(70): App\Models\home_model->HOMEditarUsuario([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->HOMEditarUsuario()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
